// Tests for the I/O contract between the Python reference and the C++ simulator.
//
// This is what can genuinely be tested in F0.1: that both sides speak the same binary format.
// Once F0.6–F0.9 are implemented, the numerical tests against the golden vectors get added here
// (F0.10).
//
// No test framework, on purpose: see DECISIONS.md D-002.

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "common.hpp"
#include "config.hpp"
#include "vector_io.hpp"

namespace {

int g_failures = 0;
int g_checks = 0;

void check(bool condition, const std::string& what) {
    ++g_checks;
    if (condition) {
        std::printf("  ok   %s\n", what.c_str());
    } else {
        std::printf("  FAIL %s\n", what.c_str());
        ++g_failures;
    }
}

// Verifies that `fn` throws ModelError. Format errors have to be detected, not slip through:
// reading a corrupt file as if it were valid produces meaningless numbers that look plausible.
template <typename Fn>
void check_throws(Fn fn, const std::string& what) {
    ++g_checks;
    try {
        fn();
        std::printf("  FAIL %s (did not throw)\n", what.c_str());
        ++g_failures;
    } catch (const zaa::ModelError&) {
        std::printf("  ok   %s\n", what.c_str());
    } catch (const std::exception& e) {
        std::printf("  FAIL %s (unexpected exception: %s)\n", what.c_str(), e.what());
        ++g_failures;
    }
}

void test_roundtrip() {
    std::printf("write/read roundtrip\n");

    zaa::Tensor original(zaa::Dtype::Int8, {3, 5});
    int8_t* data = original.as_int8_mut();
    for (std::size_t i = 0; i < original.numel(); ++i) {
        // Signed values near the limits, to catch sign errors.
        data[i] = static_cast<int8_t>((i % 2 == 0) ? static_cast<int>(i) : -127 + static_cast<int>(i));
    }

    const std::string path = "build/test_roundtrip.bin";
    zaa::write_tensor(path, original);
    const zaa::Tensor loaded = zaa::read_tensor(path);

    check(loaded.dtype() == zaa::Dtype::Int8, "dtype survives the roundtrip");
    check(loaded.shape() == original.shape(), "shape survives the roundtrip");
    check(loaded.size_bytes() == original.size_bytes(), "byte size matches");

    bool identical = true;
    const int8_t* a = original.as_int8();
    const int8_t* b = loaded.as_int8();
    for (std::size_t i = 0; i < original.numel(); ++i) {
        if (a[i] != b[i]) {
            identical = false;
            break;
        }
    }
    check(identical, "data survives bit for bit");

    check_throws([&] { (void)loaded.as_int32(); }, "reading int8 as int32 is an error");
}

void test_bad_files() {
    std::printf("invalid file detection\n");

    check_throws([] { (void)zaa::read_tensor("build/this_file_does_not_exist.bin"); },
                 "a nonexistent file throws");

    const std::string bad_path = "build/test_bad_magic.bin";
    std::FILE* f = std::fopen(bad_path.c_str(), "wb");
    if (f) {
        const char junk[40] = "this is not a ZAAV file at all";
        std::fwrite(junk, 1, sizeof(junk), f);
        std::fclose(f);
    }
    check_throws([&] { (void)zaa::read_tensor(bad_path); }, "an invalid magic throws");

    const std::string trunc_path = "build/test_truncated.bin";
    f = std::fopen(trunc_path.c_str(), "wb");
    if (f) {
        std::fwrite("ZAAV", 1, 4, f);  // correct magic, incomplete header
        std::fclose(f);
    }
    check_throws([&] { (void)zaa::read_tensor(trunc_path); }, "a truncated file throws");
}

// The vectors are generated by reference/gen_vectors.py --smoke, which the Makefile runs before
// the tests. This is the real proof that Python and C++ agree.
void test_python_interop() {
    std::printf("interoperability with the Python vectors\n");

    const std::string dir = "../vectors/smoke";
    const char* names[] = {"q", "k", "v"};

    for (const char* name : names) {
        const std::string path = dir + "/" + name + ".bin";
        const zaa::Tensor t = zaa::read_tensor(path);
        const bool shape_ok = t.shape().size() == 2 && t.shape()[0] == 8 && t.shape()[1] == 8;
        check(shape_ok, std::string(name) + ".bin from Python has shape (8, 8)");
        check(t.dtype() == zaa::Dtype::Int8, std::string(name) + ".bin from Python is int8");
        check(t.size_bytes() == 64, std::string(name) + ".bin from Python has 64 bytes of data");
    }
}

void test_config() {
    std::printf("configuration loading\n");

    const zaa::Config cfg = zaa::load_config("../sweeps/smoke.cfg");
    check(cfg.seq_len == 8, "smoke.cfg has seq_len = 8");
    check(cfg.head_dim == 8, "smoke.cfg has head_dim = 8");
    check(cfg.dataflow == "flash" || cfg.dataflow == "naive", "smoke.cfg has a valid dataflow");
    check(cfg.sram_bytes > 0, "smoke.cfg has a positive sram budget");

    check_throws([] { (void)zaa::load_config("../sweeps/does_not_exist.cfg"); },
                 "a nonexistent configuration throws");
}

}  // namespace

int main() {
    std::printf("=== test_io ===\n\n");

    try {
        test_roundtrip();
        test_bad_files();
        test_python_interop();
        test_config();
    } catch (const std::exception& e) {
        std::printf("\nuncaught exception: %s\n", e.what());
        return 1;
    }

    std::printf("\n%d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
